select * from employees;

select FIRST_NAME, SALARY from EMPLOYEES where SALARY > 700 and DEPARTMENT_ID =80;

SELECT FIRST_NAME, LAST_NAME from EMPLOYEES where SALARY > 3000 and SALARY < 6000;


SELECT FIRST_NAME, LAST_NAME,SALARY from EMPLOYEES where SALARY between 3000 and 6000;


SELECT * FROM EMPLOYEES where JOB_ID = 'IT_PROG'or JOB_ID = 'SA_REP';


