SELECT * FROM employees;

select * FROM JOB_HISTORY;

SELECT * FROM employees where FIRST_NAME = 'Steven';


--get me firstname ans lastname
SELECT FIRST_NAME, LAST_NAME from EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY from EMPLOYEES;

SELECT * FROM   DEPARTMENTS;

SELECT CITY FROM LOCATIONS;

SELECT COUNTRY_NAME, REGION_ID from  COUNTRIES;

SELECT JOB_ID, JOB_TITLE from JOBS;

select STREET_ADDRESS, POSTAL_CODE FROM  LOCATIONS;

select REGION_NAME from REGIONS;






